/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-13 22:02:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.agnitas.util.*;

public final class sidemenu_002dtiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.8.jar", Long.valueOf(1437749471000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta-standard-1.1.2.jar", Long.valueOf(1437749470000L));
    _jspx_dependants.put("jar:file:/home/openemm/webapps/openemm/WEB-INF/lib/jakarta-standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098711090000L));
    _jspx_dependants.put("/WEB-INF/agnitas-taglib.tld", Long.valueOf(1437749468000L));
    _jspx_dependants.put("jar:file:/home/openemm/webapps/openemm/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-html.tld", Long.valueOf(1172915892000L));
    _jspx_dependants.put("jar:file:/home/openemm/webapps/openemm/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-bean.tld", Long.valueOf(1172915892000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.agnitas.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey.release();
    _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.release();
    _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;

    String _jspx__sub_navigation_switch_1 = null;
    Boolean _jspx__sub_navigation_isHighlightKey_1 = null;
    String _jspx__sub_navigation_token_1 = null;
    String _jspx__sub_navigation_href_1 = null;
    String _jspx__sub_navigation_navMsg_1 = null;
    Integer _jspx__sub_navigation_index_1 = null;

    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"left_navigation_container\">\n");
      out.write("\t<ul class=\"left_navigation_level1\">\n");
      out.write("\t\t");
      //  agn:ShowNavigation
      org.agnitas.taglib.ShowNavigationTag _jspx_th_agn_005fShowNavigation_005f0 = (org.agnitas.taglib.ShowNavigationTag) _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey.get(org.agnitas.taglib.ShowNavigationTag.class);
      _jspx_th_agn_005fShowNavigation_005f0.setPageContext(_jspx_page_context);
      _jspx_th_agn_005fShowNavigation_005f0.setParent(null);
      // /sidemenu-tiles.jsp(9,2) name = navigation type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_agn_005fShowNavigation_005f0.setNavigation("sidemenu");
      // /sidemenu-tiles.jsp(9,2) name = highlightKey type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_agn_005fShowNavigation_005f0.setHighlightKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sidemenu_active}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_agn_005fShowNavigation_005f0 = _jspx_th_agn_005fShowNavigation_005f0.doStartTag();
      if (_jspx_eval_agn_005fShowNavigation_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        String _navigation_switch = null;
        Boolean _navigation_isHighlightKey = null;
        String _navigation_token = null;
        String _navigation_href = null;
        String _navigation_navMsg = null;
        Integer _navigation_index = null;
        if (_jspx_eval_agn_005fShowNavigation_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_agn_005fShowNavigation_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_agn_005fShowNavigation_005f0.doInitBody();
        }
        _navigation_switch = (String) _jspx_page_context.findAttribute("_navigation_switch");
        _navigation_isHighlightKey = (Boolean) _jspx_page_context.findAttribute("_navigation_isHighlightKey");
        _navigation_token = (String) _jspx_page_context.findAttribute("_navigation_token");
        _navigation_href = (String) _jspx_page_context.findAttribute("_navigation_href");
        _navigation_navMsg = (String) _jspx_page_context.findAttribute("_navigation_navMsg");
        _navigation_index = (Integer) _jspx_page_context.findAttribute("_navigation_index");
        do {
          out.write("\n");
          out.write("\t\t\t");
          //  agn:ShowByPermission
          org.agnitas.taglib.ShowByPermissionTag _jspx_th_agn_005fShowByPermission_005f0 = (org.agnitas.taglib.ShowByPermissionTag) _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.get(org.agnitas.taglib.ShowByPermissionTag.class);
          _jspx_th_agn_005fShowByPermission_005f0.setPageContext(_jspx_page_context);
          _jspx_th_agn_005fShowByPermission_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_agn_005fShowNavigation_005f0);
          // /sidemenu-tiles.jsp(10,3) name = token type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_agn_005fShowByPermission_005f0.setToken((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int _jspx_eval_agn_005fShowByPermission_005f0 = _jspx_th_agn_005fShowByPermission_005f0.doStartTag();
          if (_jspx_eval_agn_005fShowByPermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("\n");
              out.write("\t\t\t\t");

					String cssClassPostfix = _navigation_isHighlightKey.booleanValue() ? "_active" : "_no";
				
              out.write("\n");
              out.write("\t\t\t\t\n");
              out.write("\t\t\t\t<li>\n");
              out.write("\t\t\t\t\t");
              //  html:link
              org.apache.struts.taglib.html.LinkTag _jspx_th_html_005flink_005f0 = (org.apache.struts.taglib.html.LinkTag) _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.get(org.apache.struts.taglib.html.LinkTag.class);
              _jspx_th_html_005flink_005f0.setPageContext(_jspx_page_context);
              _jspx_th_html_005flink_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_agn_005fShowByPermission_005f0);
              // /sidemenu-tiles.jsp(17,5) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_html_005flink_005f0.setPage((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_href}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              // /sidemenu-tiles.jsp(17,5) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_html_005flink_005f0.setStyleClass( "left_navigation_level1" + cssClassPostfix + "_round" );
              int _jspx_eval_html_005flink_005f0 = _jspx_th_html_005flink_005f0.doStartTag();
              if (_jspx_eval_html_005flink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_html_005flink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.pushBody();
                  _jspx_th_html_005flink_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                  _jspx_th_html_005flink_005f0.doInitBody();
                }
                do {
                  out.write("\n");
                  out.write("\t\t\t\t\t\t");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_html_005flink_005f0, _jspx_page_context))
                    return;
                  out.write("\t\n");
                  out.write("\t\t\t\t\t\t");
                  if (_jspx_meth_c_005fif_005f1(_jspx_th_html_005flink_005f0, _jspx_page_context))
                    return;
                  out.write("\t\n");
                  out.write("\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_html_005flink_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_html_005flink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_html_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.reuse(_jspx_th_html_005flink_005f0);
                return;
              }
              _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.reuse(_jspx_th_html_005flink_005f0);
              out.write(" \n");
              out.write("\t\t\t\t\t\n");
              out.write("\t\t\t\t\t");
              //  c:if
              org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_agn_005fShowByPermission_005f0);
              // /sidemenu-tiles.jsp(26,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_isHighlightKey}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("\t\t\t\t\t\t<ul class=\"left_navigation_level2\">\n");
                  out.write("\t\t\t\t\t\t\t");
                  //  agn:ShowNavigation
                  org.agnitas.taglib.ShowNavigationTag _jspx_th_agn_005fShowNavigation_005f1 = (org.agnitas.taglib.ShowNavigationTag) _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey.get(org.agnitas.taglib.ShowNavigationTag.class);
                  _jspx_th_agn_005fShowNavigation_005f1.setPageContext(_jspx_page_context);
                  _jspx_th_agn_005fShowNavigation_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
                  // /sidemenu-tiles.jsp(28,7) name = navigation type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_agn_005fShowNavigation_005f1.setNavigation((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_navMsg}Sub", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  // /sidemenu-tiles.jsp(28,7) name = highlightKey type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_agn_005fShowNavigation_005f1.setHighlightKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sidemenu_sub_active}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  // /sidemenu-tiles.jsp(28,7) name = prefix type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_agn_005fShowNavigation_005f1.setPrefix("_sub");
                  int _jspx_eval_agn_005fShowNavigation_005f1 = _jspx_th_agn_005fShowNavigation_005f1.doStartTag();
                  if (_jspx_eval_agn_005fShowNavigation_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    String _sub_navigation_switch = null;
                    Boolean _sub_navigation_isHighlightKey = null;
                    String _sub_navigation_token = null;
                    String _sub_navigation_href = null;
                    String _sub_navigation_navMsg = null;
                    Integer _sub_navigation_index = null;
                    if (_jspx_eval_agn_005fShowNavigation_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                      out = _jspx_page_context.pushBody();
                      _jspx_th_agn_005fShowNavigation_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                      _jspx_th_agn_005fShowNavigation_005f1.doInitBody();
                    }
                    _sub_navigation_switch = (String) _jspx_page_context.findAttribute("_sub_navigation_switch");
                    _sub_navigation_isHighlightKey = (Boolean) _jspx_page_context.findAttribute("_sub_navigation_isHighlightKey");
                    _sub_navigation_token = (String) _jspx_page_context.findAttribute("_sub_navigation_token");
                    _sub_navigation_href = (String) _jspx_page_context.findAttribute("_sub_navigation_href");
                    _sub_navigation_navMsg = (String) _jspx_page_context.findAttribute("_sub_navigation_navMsg");
                    _sub_navigation_index = (Integer) _jspx_page_context.findAttribute("_sub_navigation_index");
                    do {
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t\t");
                      //  agn:ShowByPermission
                      org.agnitas.taglib.ShowByPermissionTag _jspx_th_agn_005fShowByPermission_005f1 = (org.agnitas.taglib.ShowByPermissionTag) _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.get(org.agnitas.taglib.ShowByPermissionTag.class);
                      _jspx_th_agn_005fShowByPermission_005f1.setPageContext(_jspx_page_context);
                      _jspx_th_agn_005fShowByPermission_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_agn_005fShowNavigation_005f1);
                      // /sidemenu-tiles.jsp(29,8) name = token type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_agn_005fShowByPermission_005f1.setToken((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_sub_navigation_token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                      int _jspx_eval_agn_005fShowByPermission_005f1 = _jspx_th_agn_005fShowByPermission_005f1.doStartTag();
                      if (_jspx_eval_agn_005fShowByPermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        do {
                          out.write("\n");
                          out.write("\t\t\t\t\t\t\t\t\t");

										String subCssClassPostfix = _sub_navigation_isHighlightKey.booleanValue() ? "_active" : "_no";
									
                          out.write("\n");
                          out.write("\t\t\t\t\t\t\t\t\t<li>\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t");
                          //  html:link
                          org.apache.struts.taglib.html.LinkTag _jspx_th_html_005flink_005f1 = (org.apache.struts.taglib.html.LinkTag) _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.get(org.apache.struts.taglib.html.LinkTag.class);
                          _jspx_th_html_005flink_005f1.setPageContext(_jspx_page_context);
                          _jspx_th_html_005flink_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_agn_005fShowByPermission_005f1);
                          // /sidemenu-tiles.jsp(34,10) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_html_005flink_005f1.setPage((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_sub_navigation_href}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          // /sidemenu-tiles.jsp(34,10) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_html_005flink_005f1.setStyleClass( "left_navigation_level2" + subCssClassPostfix );
                          int _jspx_eval_html_005flink_005f1 = _jspx_th_html_005flink_005f1.doStartTag();
                          if (_jspx_eval_html_005flink_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_html_005flink_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_html_005flink_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_html_005flink_005f1.doInitBody();
                            }
                            do {
                              out.write("\n");
                              out.write("\t\t\t\t\t\t\t\t\t\t\t");
                              if (_jspx_meth_c_005fif_005f3(_jspx_th_html_005flink_005f1, _jspx_page_context))
                              return;
                              out.write("\n");
                              out.write("\t\t\t\t\t\t\t\t\t\t\t");
                              if (_jspx_meth_c_005fif_005f4(_jspx_th_html_005flink_005f1, _jspx_page_context))
                              return;
                              out.write("\n");
                              out.write("\t\t\t\t\t\t\t\t\t\t");
                              int evalDoAfterBody = _jspx_th_html_005flink_005f1.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_html_005flink_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_html_005flink_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.reuse(_jspx_th_html_005flink_005f1);
                            return;
                          }
                          _005fjspx_005ftagPool_005fhtml_005flink_0026_005fstyleClass_005fpage.reuse(_jspx_th_html_005flink_005f1);
                          out.write("\n");
                          out.write("\t\t\t\t\t\t\t\t\t</li>\n");
                          out.write("\t\t\t\t\t\t\t\t");
                          int evalDoAfterBody = _jspx_th_agn_005fShowByPermission_005f1.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                      }
                      if (_jspx_th_agn_005fShowByPermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.reuse(_jspx_th_agn_005fShowByPermission_005f1);
                        return;
                      }
                      _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.reuse(_jspx_th_agn_005fShowByPermission_005f1);
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t");
                      int evalDoAfterBody = _jspx_th_agn_005fShowNavigation_005f1.doAfterBody();
                      _sub_navigation_switch = (String) _jspx_page_context.findAttribute("_sub_navigation_switch");
                      _sub_navigation_isHighlightKey = (Boolean) _jspx_page_context.findAttribute("_sub_navigation_isHighlightKey");
                      _sub_navigation_token = (String) _jspx_page_context.findAttribute("_sub_navigation_token");
                      _sub_navigation_href = (String) _jspx_page_context.findAttribute("_sub_navigation_href");
                      _sub_navigation_navMsg = (String) _jspx_page_context.findAttribute("_sub_navigation_navMsg");
                      _sub_navigation_index = (Integer) _jspx_page_context.findAttribute("_sub_navigation_index");
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                    if (_jspx_eval_agn_005fShowNavigation_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                      out = _jspx_page_context.popBody();
                    }
                  }
                  if (_jspx_th_agn_005fShowNavigation_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey.reuse(_jspx_th_agn_005fShowNavigation_005f1);
                    return;
                  }
                  _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fprefix_005fnavigation_005fhighlightKey.reuse(_jspx_th_agn_005fShowNavigation_005f1);
                  out.write("\n");
                  out.write("\t\t\t\t\t\t</ul> \n");
                  out.write("\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              out.write("\n");
              out.write("\t\t\t\t</li>\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_agn_005fShowByPermission_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_agn_005fShowByPermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.reuse(_jspx_th_agn_005fShowByPermission_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fagn_005fShowByPermission_0026_005ftoken.reuse(_jspx_th_agn_005fShowByPermission_005f0);
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_agn_005fShowNavigation_005f0.doAfterBody();
          _navigation_switch = (String) _jspx_page_context.findAttribute("_navigation_switch");
          _navigation_isHighlightKey = (Boolean) _jspx_page_context.findAttribute("_navigation_isHighlightKey");
          _navigation_token = (String) _jspx_page_context.findAttribute("_navigation_token");
          _navigation_href = (String) _jspx_page_context.findAttribute("_navigation_href");
          _navigation_navMsg = (String) _jspx_page_context.findAttribute("_navigation_navMsg");
          _navigation_index = (Integer) _jspx_page_context.findAttribute("_navigation_index");
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_agn_005fShowNavigation_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_agn_005fShowNavigation_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey.reuse(_jspx_th_agn_005fShowNavigation_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fagn_005fShowNavigation_0026_005fnavigation_005fhighlightKey.reuse(_jspx_th_agn_005fShowNavigation_005f0);
      out.write("\n");
      out.write("\t</ul>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005flink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005flink_005f0);
    // /sidemenu-tiles.jsp(18,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty _navigation_plugin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_bean_005fmessage_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /sidemenu-tiles.jsp(19,7) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_navMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005flink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005flink_005f0);
    // /sidemenu-tiles.jsp(21,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty _navigation_plugin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_agn_005fmessage_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_agn_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  agn:message
    org.agnitas.emm.extension.taglib.ExtensionI18NTag _jspx_th_agn_005fmessage_005f0 = (org.agnitas.emm.extension.taglib.ExtensionI18NTag) _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.get(org.agnitas.emm.extension.taglib.ExtensionI18NTag.class);
    _jspx_th_agn_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_agn_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /sidemenu-tiles.jsp(22,7) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_agn_005fmessage_005f0.setKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_navMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /sidemenu-tiles.jsp(22,7) name = plugin type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_agn_005fmessage_005f0.setPlugin((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_navigation_plugin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_agn_005fmessage_005f0 = _jspx_th_agn_005fmessage_005f0.doStartTag();
    if (_jspx_th_agn_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.reuse(_jspx_th_agn_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.reuse(_jspx_th_agn_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005flink_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005flink_005f1);
    // /sidemenu-tiles.jsp(35,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty _sub_navigation_plugin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_bean_005fmessage_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /sidemenu-tiles.jsp(36,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f1.setKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_sub_navigation_navMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
    if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005flink_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005flink_005f1);
    // /sidemenu-tiles.jsp(38,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty _sub_navigation_plugin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_agn_005fmessage_005f1(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_agn_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  agn:message
    org.agnitas.emm.extension.taglib.ExtensionI18NTag _jspx_th_agn_005fmessage_005f1 = (org.agnitas.emm.extension.taglib.ExtensionI18NTag) _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.get(org.agnitas.emm.extension.taglib.ExtensionI18NTag.class);
    _jspx_th_agn_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_agn_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /sidemenu-tiles.jsp(39,12) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_agn_005fmessage_005f1.setKey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_sub_navigation_navMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /sidemenu-tiles.jsp(39,12) name = plugin type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_agn_005fmessage_005f1.setPlugin((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_sub_navigation_plugin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_agn_005fmessage_005f1 = _jspx_th_agn_005fmessage_005f1.doStartTag();
    if (_jspx_th_agn_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.reuse(_jspx_th_agn_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fagn_005fmessage_0026_005fplugin_005fkey_005fnobody.reuse(_jspx_th_agn_005fmessage_005f1);
    return false;
  }
}
