pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["action_changing_recipient_prof.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Defining actions &#62; Action: Changing recipient profile","Action: Changing recipient profile",""],
["action_including_a_script_in_a.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Defining actions &#62; Action: Including a script in an action","Action: Including a script in an action",""],
["action_triggering_an_action-ba.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Defining actions &#62; Action: Triggering an action-based mailing","Action: Triggering an action-based mailing",""],
["adding_contents_to_a_module_ty.htm","Content Manager &#62; Module types &#62; Adding contents to a module type and saving it as a content module","Adding contents to a module type and saving it as a content module",""],
["advanced_form_layout.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Advanced form layout","Advanced form layout",""],
["appendix_a_agnitas-tags.htm","Appendix A: AGNITAS-Tags","Appendix A: AGNITAS-Tags",""],
["archives_-_grouping_mailings.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings","Archives - Grouping mailings",""],
["assigning_a_content_module_to_.htm","Content Manager &#62; Content modules &#62; CM categories &#62; Assigning a content module to a CM category","Assigning a content module to a CM category",""],
["assigning_the_csv_columns_to_t.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; The import assistant &#62; Assigning the CSV columns to the database columns","Assigning the CSV columns to the database columns",""],
["assigning_user_rights2.htm","Administration - Configuring the system &#62; Users &#62; Assigning user rights","Assigning user rights",""],
["assign_existing_mailing.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Assign mailing to a archive &#62; Assign existing mailing","Assign existing mailing",""],
["assign_mailing_to_a_archive.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Assign mailing to a archive","Assign mailing to a archive",""],
["assign_new_mailing.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Assign mailing to a archive &#62; Assign new mailing","Assign new mailing",""],
["auto-export.htm","Recipients - Managing customer data &#62; Export function for recipient data &#62; Auto-Export","Auto-Export",""],
["auto-import.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Auto-Import","Auto-Import",""],
["automatic_date-based_mailing_-.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Automatic date-based mailings - an example","Automatic date-based mailings - an example",""],
["automatic_mailing_-_an_example.htm","Forms &#38; Actions &#62; Automatic mailing - An example","Automatic mailing - An example",""],
["automatic_update_of_openemm.htm","Administration - Configuring the system &#62; Automatic update of OpenEMM","Automatic update of OpenEMM",""],
["blacklist_-_do_not_mail.htm","Recipients - Managing customer data &#62; Blacklist - Do not mail","Blacklist - Do not mail",""],
["bounce-filter.htm","Administration - Configuring the system &#62; Bounce-Filter","Bounce Filter",""],
["calling_up_a_form.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Amend a profile &#62; Calling up a form","Calling up a form",""],
["calling_up_the_registration_f2.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Subscribing with double opt-in &#62; Calling up the registration form","Calling up the registration form",""],
["calling_up_the_registration_fo.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Opt-in &#62; Calling up the registration form","Calling up the registration form",""],
["calling_up_the_unsubscribe_for.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Unsubscribe &#62; Calling up the unsubscribe form","Calling up the unsubscribe form",""],
["click_summation_for_trackable_.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links &#62; Click summation for trackable links","Click summation for trackable links",""],
["closed-loop_marketing_-_an_exa.htm","Forms &#38; Actions &#62; Closed-loop marketing","Closed-loop marketing",""],
["cm_categories.htm","Content Manager &#62; Content modules &#62; CM categories","CM categories",""],
["cm_templates.htm","Content Manager &#62; CM templates","CM templates",""],
["combined_search_rules_with_bra.htm","Target groups - Dynamic filters &#62; Combined search rules with brackets","Combined search rules with brackets",""],
["combining_search_rules.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Searching for fields &#62; Combining search rules","Combining search rules",""],
["comparing_mailings2.htm","Statistics - To gain a broad view &#62; Comparing mailings","Comparing mailings",""],
["comparing_target_groups_openemm.htm","Statistics - To gain a broad view &#62; Mailing statistics &#62; Comparing target groups","Comparing target groups",""],
["connecting_links_to_actions.htm","Forms &#38; Actions &#62; Closed-loop marketing &#62; Connecting links to actions","Connecting links to actions",""],
["content_manager.htm","Content Manager","Content Manager",""],
["content_modules.htm","Content Manager &#62; Content modules","Content modules",""],
["copying_a_mailing.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Copying a mailing","Copying a mailing",""],
["copying_of_target_groups.htm","Target groups - Dynamic filters &#62; Copying of target groups","Copying of target groups",""],
["create_an_action-based_mailing.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Subscribing with double opt-in &#62; Create an action-based mailing","Create an action-based mailing",""],
["create_a_link_in_the_html_vers.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links &#62; Create a link in the HTML version","Create a link in the HTML version",""],
["create_a_link_in_the_text_vers.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links &#62; Create a link in the text version","Create a link in the text version",""],
["create_a_mailing_list_from_a_t.htm","Target groups - Dynamic filters &#62; Create a mailing list from a target group or delete recipients","Create a mailing list from a target group or delete recipients",""],
["create_a_new_archive.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Managing archives &#62; Create a new archive","Create a new archive",""],
["create_a_new_cm_category.htm","Content Manager &#62; Content modules &#62; CM categories &#62; Create a new CM category","Create a new CM category",""],
["create_a_new_module_type.htm","Content Manager &#62; Module types &#62; Create a new module type","Create a new module type",""],
["create_new_mailing_using_the_w.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Create new mailing using the wizard","Create new mailing using the wizard",""],
["create_new_recipients.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Create new recipients","Create new recipients",""],
["create_trackable_and_non-track.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links &#62; Create trackable and non-trackable links","Create trackable and non-trackable links",""],
["create__edit_and_send_mailings.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings","Create, edit and send mailings",""],
["creating_administrators_and_te.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Creating administrators and test distribution lists","Creating administrators and test distribution lists",""],
["creating_and_managing_target_g.htm","Target groups - Dynamic filters &#62; Creating and managing target groups","Creating and managing target groups",""],
["creating_a_basic_mailing.htm","Forms &#38; Actions &#62; Automatic mailing - An example &#62; Creating a basic mailing","Creating a basic mailing",""],
["creating_a_csv-file.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a CSV-file","Creating a CSV-file",""],
["creating_a_follow-up_mailing.htm","Forms &#38; Actions &#62; Automatic mailing - An example &#62; Creating a follow-up mailing","Creating a follow-up mailing",""],
["creating_a_form_to_display_dat.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Amend a profile &#62; Creating a form to display data","Creating a form to display data",""],
["creating_a_form_to_enter_data.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Opt-in &#62; Creating a form to enter data","Creating a form to enter data",""],
["creating_a_form_to_save_data.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Amend a profile &#62; Creating a form to save data","Creating a form to save data",""],
["creating_a_form_to_save_data2.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Opt-in &#62; Creating a form to save data","Creating a form to save data",""],
["creating_a_html_form_dynamical.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Advanced form layout &#62; Creating a HTML form dynamically","Creating a HTML form dynamically",""],
["creating_a_mailing_list.htm","Mailing lists - Managing list subscription &#62; Creating a mailing list","Creating a mailing list",""],
["creating_a_new_action.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Amend a profile &#62; Creating a new action","Creating a new action",""],
["creating_a_new_action2.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Opt-in &#62; Creating a new action","Creating a new action",""],
["creating_a_new_action3.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Unsubscribe &#62; Creating a new action","Creating a new action",""],
["creating_a_new_content_module.htm","Content Manager &#62; Content modules &#62; Creating a new content module","Creating a new content module",""],
["creating_a_new_import_profile.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile","Creating a new import profile",""],
["creating_a_new_mailing.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing","Creating a new mailing",""],
["creating_a_new_template.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template","Creating a new template",""],
["creating_a_new_user_and_changi.htm","Administration - Configuring the system &#62; Users &#62; Creating a new user and changing password","Creating a new user and changing password",""],
["creating_customized_mailings.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating customized mailings","Creating customized mailings",""],
["creating_new_actions.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Subscribing with double opt-in &#62; Creating new actions","Creating new actions",""],
["creating_new_fields.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Extending recipient&#39;s profiles &#62; Creating new fields","Creating new fields",""],
["creating_new_forms.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Subscribing with double opt-in &#62; Creating new forms","Creating new forms",""],
["creating_new_forms2.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Unsubscribe &#62; Creating new forms","Creating new forms",""],
["creating_text_and_html_modules.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Inserting content &#62; Creating text and HTML modules","Creating text and HTML modules",""],
["date_functions.htm","Target groups - Dynamic filters &#62; Search rule setup &#62; Date functions","Date functions",""],
["deactivating_and_uninstalling_.htm","Administration - Configuring the system &#62; Plugin Manager (only for license users) &#62; Deactivating and uninstalling a plugin","Deactivating and uninstalling a plugin",""],
["defining_actions.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Defining actions","Defining actions",""],
["defining_actions2.htm","Forms &#38; Actions &#62; Closed-loop marketing &#62; Defining actions","Defining actions",""],
["defining_actions3.htm","Forms &#38; Actions &#62; Automatic mailing - An example &#62; Defining actions","Defining actions",""],
["deleting_an_archive.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Managing archives &#62; Deleting an archive","Deleting an archive",""],
["deleting_a_cm_category.htm","Content Manager &#62; Content modules &#62; CM categories &#62; Deleting a CM category","Deleting a CM category",""],
["deleting_a_content_module.htm","Content Manager &#62; Content modules &#62; Deleting a content module","Deleting a content module",""],
["deleting_a_mailing_list.htm","Mailing lists - Managing list subscription &#62; Deleting a mailing list","Deleting a mailing list",""],
["deleting_a_module_type.htm","Content Manager &#62; Module types &#62; Deleting a module type","Deleting a module type",""],
["deleting_a_recipient.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Deleting a recipient","Deleting a recipient",""],
["deleting_a_template.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template &#62; Deleting a template","Deleting a template",""],
["deleting_existing_fields.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Extending recipient&#39;s profiles &#62; Deleting existing fields","Deleting existing fields",""],
["detailed_recipient_statistics_openemm.htm","Statistics - To gain a broad view &#62; Recipient statistics &#62; Detailed recipient statistics","Detailed recipient statistics",""],
["determining_the_csv-file_setti.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile &#62; Determining the CSV-file settings","Determining the CSV-file settings",""],
["determining_the_process_settin.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile &#62; Determining the process settings","Determining the process settings",""],
["display_and_amend_details.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Managing archives &#62; Display and amend details","Display and amend details",""],
["domain_statistics.htm","Statistics - To gain a broad view &#62; Domain statistics","Domain statistics",""],
["drop-down_list_for_relational_.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Searching for fields &#62; Drop-down list for relational operators","Drop-down list for relational operators",""],
["drop-down_list_instead_of_entr.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Advanced form layout &#62; Drop-down list instead of entry field","Drop-down list instead of entry field",""],
["dynamic_content_generation.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Dynamic content generation","Dynamic content generation",""],
["dynamic_text_module.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Using text modules &#62; Dynamic text module","Dynamic text module",""],
["editing_cm_templates.htm","Content Manager &#62; CM templates &#62; Editing CM templates","Editing CM templates",""],
["editing_recipient_profile.htm","Forms &#38; Actions &#62; Closed-loop marketing &#62; Editing recipient profile","Editing recipient profile",""],
["edit_recipient_profile.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Edit recipient profile","Edit recipient profile",""],
["entering_basic_data.htm","Content Manager &#62; Module types &#62; Entering basic data","Entering basic data",""],
["entering_basic_data2.htm","Content Manager &#62; Content modules &#62; Entering basic data","Entering basic data",""],
["entering_basic_mailing_data.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Entering basic mailing data","Entering basic mailing data",""],
["entering_basic_template_data.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template &#62; Entering basic template data","Entering basic template data",""],
["entering_further_mailing_data.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Entering further mailing data","Entering further mailing data",""],
["entering_further_template_data.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template &#62; Entering further template data","Entering further template data",""],
["en_openemm2015v1_headerframe.htm","AGNITAS AG OpenEMM 2015 Manual","OpenEMM Online-Help Search ",""],
["errorhandling.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; The import assistant &#62; Error handling","Error handling",""],
["example_form_for_a_user_profil.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Amend a profile","Example form: Amend a profile",""],
["example_form_for_unsubscribing.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Unsubscribe","Example form: Unsubscribe",""],
["example_opt-in_form.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Opt-in","Example form: Opt-in",""],
["example_subscribing_with_doubl.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Example form: Subscribing with double opt-in","Example form: Subscribing with double opt-in",""],
["exporting_statistical_data.htm","Statistics - To gain a broad view &#62; Exporting statistical data","Exporting statistical data",""],
["export_function_for_recipient_.htm","Recipients - Managing customer data &#62; Export function for recipient data","Export function for recipient data",""],
["extending_recipients_profiles.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Extending recipient&#39;s profiles","Extending recipient&#39;s profiles",""],
["feedback_analysis_openemm.htm","Statistics - To gain a broad view &#62; Mailing statistics &#62; Feedback analysis","Feedback analysis",""],
["field_drop-down_list.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Searching for fields &#62; Field drop-down list","Field drop-down list",""],
["forms.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms","Forms",""],
["forms_-_recipient_management.htm","Forms &#38; Actions &#62; Forms - Recipient management","Forms - Recipient management",""],
["form_of_address_-_individual_g.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating customized mailings &#62; Form of address - Individual greetings","Form of address - Individual greetings",""],
["fullview_always_display_html_m.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Fullview: Always display HTML mails correctly","Fullview: Always display HTML mails correctly",""],
["functions_of_the_produktname.htm","OpenEMM - The Basics &#62; Functions of the OpenEMM","Functions of the OpenEMM",""],
["further_details_for_creating_t.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template &#62; Further details for creating templates","Further details for creating templates",""],
["general_information.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Show recipient profile &#62; General information","General information",""],
["handling_with_duplicates.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile &#62; Handling with duplicates","Handling with duplicates",""],
["heatmap_openemm.htm","Statistics - To gain a broad view &#62; Mailing statistics &#62; Heatmap","Heatmap",""],
["how_do_recipients_get_into_you.htm","Recipients - Managing customer data &#62; More than just e-mail addresses &#62; How do recipients get into your database?","How do recipients get into your database?",""],
["importing_the_csv-file.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; The import assistant &#62; Importing the CSV-file","Importing the CSV-file",""],
["import_dialog_structure.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Import dialog structure","Import dialog structure",""],
["import_function_for_recipient_.htm","Recipients - Managing customer data &#62; Import function for recipient data","Import function for recipient data",""],
["inserting_agnitas-tags.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating customized mailings &#62; Inserting AGNITAS-Tags","Inserting AGNITAS-Tags",""],
["inserting_a_text_module_using_.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Using text modules &#62; Inserting a text module using AGNITAS-Tags","Inserting a text module using AGNITAS-Tags",""],
["inserting_content.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Inserting content","Inserting content",""],
["insert_agnitas-tags_into_track.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links &#62; Building AGNITAS tags into trackable links","Building AGNITAS tags into trackable links",""],
["installing_and_activating_a_pl.htm","Administration - Configuring the system &#62; Plugin Manager (only for license users) &#62; Installing and activating a plugin","Installing and activating a plugin",""],
["ip_statistics.htm","Statistics - To gain a broad view &#62; IP overview","IP overview",""],
["is_and_null_or_not_null.htm","Target groups - Dynamic filters &#62; Search rule setup &#62; IS and NULL or NOT NULL","IS and NULL or NOT NULL",""],
["linking_actions_and_trackable_.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Linking actions and trackable links","Linking actions and trackable links",""],
["linking_target_groups.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Linking target groups","Linking target groups",""],
["list_existing_mailings.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; List existing mailings","List of existing mailings",""],
["list_split_using_mod.htm","Target groups - Dynamic filters &#62; Search rule setup &#62; List split using MOD","List split using MOD",""],
["mailings_-_sending_out_newslet.htm","Mailings - Sending out newsletters","Mailings - Sending out newsletters",""],
["mailings_under_control.htm","OpenEMM - The Basics &#62; Introduction to the OpenEMM","Introduction to the OpenEMM",""],
["mailing_lists_-_managing_list_.htm","Mailing lists - Managing list subscription","Mailing lists - Managing list subscription",""],
["mailing_lists_and_recipient_ty.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Show recipient profile &#62; Mailing lists and recipient types","Mailing lists and recipient types",""],
["mailing_statistics_openemm.htm","Statistics - To gain a broad view &#62; Mailing statistics","Mailing statistics",""],
["maintain_recipients_profile_wi.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions","Actions - Maintain recipient&#39;s profile",""],
["managing_actions.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Defining actions &#62; Managing actions","Managing actions",""],
["managing_archives.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Managing archives","Managing archives",""],
["managing_a_profile__deleting_a.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Managing a profile, deleting a profile","Managing a profile, deleting a profile",""],
["managing_fields.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile &#62; Manage columns","Manage columns",""],
["managing_forms.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Managing forms","Managing forms",""],
["managing_profile_fields.htm","Administration - Configuring the system &#62; Managing profile fields","Managing profile fields",""],
["managing_recipients.htm","Recipients - Managing customer data &#62; Managing recipients","Managing recipients",""],
["managing_user.htm","Administration - Configuring the system &#62; Users &#62; Managing user","Managing users",""],
["modifying_a_mailing_list.htm","Mailing lists - Managing list subscription &#62; Modifying a mailing list","Modifying a mailing list",""],
["module_types.htm","Content Manager &#62; Module types","Module types",""],
["more_than_just_e-mail_addresse.htm","Recipients - Managing customer data &#62; More than just e-mail addresses","More than just e-mail addresses",""],
["navigation_bar_and_mailing_elements.htm","Handling - Navigate through OpenEMM &#62; Navigation bar and mailing elements","Navigation bar and mailing elements",""],
["online_help.htm","Handling - Navigate through OpenEMM &#62; Online Help","Online Help",""],
["other_profile_data.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Show recipient profile &#62; Other profile data","Other profile data",""],
["overview_of_agnitas-tags.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating customized mailings &#62; Overview of AGNITAS-Tags","Overview of AGNITAS-Tags",""],
["overview_this_is_how_the_modul.htm","OpenEMM - The Basics &#62; Overview: This is how the modules interact","Overview: Description of the different functional areas",""],
["planning_fields_properly.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; Extending recipient&#39;s profiles &#62; Planning fields properly","Planning fields properly",""],
["plugin_manager.htm","Administration - Configuring the system &#62; Plugin Manager (only for license users)","Plugin Manager",""],
["preview_-_for_in-depth_checkin.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Testing and sending a mailing &#62; Preview - For in-depth checking","Preview - For in-depth checking",""],
["produktname_-_the_basics.htm","OpenEMM - The Basics","OpenEMM - The Basics",""],
["recipients_-_managing_customer.htm","Recipients - Managing customer data","Recipients - Managing customer data",""],
["recipient_statistics_openemm.htm","Statistics - To gain a broad view &#62; Recipient statistics","Recipient statistics",""],
["saving_and_copying_module_type.htm","Content Manager &#62; Module types &#62; Saving and copying module types","Saving and copying module types",""],
["saving_and_copying_templates.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Creating a new template &#62; Saving and copying templates","Saving and copying templates",""],
["saving_a_content_moduke_and_as.htm","Content Manager &#62; Content modules &#62; Saving a content module and assigning it to a mailing, copyin a content module","Saving a content module and assigning it to a mailing, copyin a content module",""],
["saving_a_new_mailing.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Saving a new mailing","Saving a new mailing",""],
["searching_for_fields.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Searching for fields","Searching for fields",""],
["searching_for_mailing_lists.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Searching for mailing lists","Searching for mailing lists",""],
["searching_for_recipients.htm","Recipients - Managing customer data &#62; Searching for recipients","Searching for recipients",""],
["search_by_recipient_status.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Search by recipient status","Search by recipient status",""],
["search_by_recipient_type.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Search by recipient type","Search by recipient type",""],
["search_by_target-group.htm","Recipients - Managing customer data &#62; Searching for recipients &#62; Search by target-group","Search by target-group",""],
["search_rule_setup.htm","Target groups - Dynamic filters &#62; Search rule setup","Search rule setup",""],
["selecting_target_groups.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Creating a new mailing &#62; Selecting target groups","Selecting target groups",""],
["selection_of_mailing_lists.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; The import assistant &#62; Selection of mailing lists","Selection of mailing lists",""],
["sending_file_attachments.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Sending file attachments","Sending file attachments",""],
["sending_normal_file_attachment.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Sending file attachments &#62; Sending normal file attachment","Sending normal file attachment",""],
["sending_out_test_mails.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Testing and sending a mailing &#62; Sending out test mails","Sending out test mails",""],
["sending_the_last_newsletter_ju.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; Sending the last newsletter just after subscription","Sending the last newsletter just after subscription",""],
["send_mailing.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Testing and sending a mailing &#62; Send mailing","Send mailing",""],
["settings_-_configuring_the_sys.htm","Administration - Configuring the system","Administration - Configuring the system",""],
["settings_for_e-mail_and_gender.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; Creating a new import profile &#62; Settings for e-mail and gender","Settings for e-mail and gender",""],
["show_available_cm_templates.htm","Content Manager &#62; CM templates &#62; Show available CM templates","Show available CM templates",""],
["show_available_content_modules.htm","Content Manager &#62; Content modules &#62; Show available content modules","Show available content modules",""],
["show_available_module_types.htm","Content Manager &#62; Module types &#62; Show available module types","Show available module types",""],
["show_recipient_profile.htm","Recipients - Managing customer data &#62; Managing recipients &#62; Show recipient profile","Show recipient profile",""],
["show_template_data.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Show template data","Show template data",""],
["sites__actions.htm","Forms &#38; Actions","Sites &#38; Actions",""],
["starting_the_produktname.htm","Handling - Navigate through OpenEMM &#62; Starting the OpenEMM","Starting the OpenEMM",""],
["statistical_evaluation.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; Statistical evaluation","Statistical evaluation",""],
["statistics_-_to_gain_a_broad_v.htm","Statistics - To gain a broad view","Statistics - To gain a broad view",""],
["subscription_via_e-mail.htm","Administration - Configuring the system &#62; Bounce-Filter &#62; Subscription via e-mail","Subscription via e-mail",""],
["target_groups_-_dynamic_filter.htm","Target groups - Dynamic filters","Target groups - Dynamic filters",""],
["templates_-_re-usable_text_mod.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules","Templates - Re-usable text modules",""],
["testing_and_sending_a_mailing.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Testing and sending a mailing","Testing and sending a mailing",""],
["the_import_assistant.htm","Recipients - Managing customer data &#62; Import function for recipient data &#62; The import assistant","The import assistant",""],
["the_plugins_at_a_glance.htm","Administration - Configuring the system &#62; Plugin Manager (only for license users) &#62; The plugins at a glance","The plugins at a glance",""],
["this_is_how_forms_work.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; Forms &#62; This is how forms work","This is how forms work",""],
["types_of_address.htm","Recipients - Managing customer data &#62; Forms of salutation","Forms of salutation",""],
["uploading_new_cm_templates.htm","Content Manager &#62; CM templates &#62; Uploading new CM templates","Uploading new CM templates",""],
["user-defined_fields.htm","Recipients - Managing customer data &#62; More than just e-mail addresses &#62; User-defined fields","User-defined fields",""],
["users.htm","Administration - Configuring the system &#62; Users","Users",""],
["user_log.htm","Administration - Configuring the system &#62; User log","User log",""],
["user_self-administration.htm","Handling - Navigate through OpenEMM &#62; User Self-Administration","User Self-Administration",""],
["using_cm_templates_in_mailings.htm","Content Manager &#62; Using CM templates in mailings","Using CM templates in mailings",""],
["using_graphic_elements.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using graphic elements","Using graphic elements",""],
["using_templates.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Using templates","Using templates",""],
["using_text_modules.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; Using text modules","Using text modules",""],
["using_the_produktname_to_contr.htm","Handling - Navigate through OpenEMM","Handling - Navigate through OpenEMM",""],
["using_trackable_links.htm","Mailings - Sending out newsletters &#62; Create, edit and send mailings &#62; Using trackable links","Using trackable links",""],
["what_are_archives_.htm","Mailings - Sending out newsletters &#62; Archives - Grouping mailings &#62; What are archives?","What are archives?",""],
["what_are_templates_.htm","Mailings - Sending out newsletters &#62; Templates - Re-usable text modules &#62; What are templates?","What are templates?",""],
["what_are_the_available_statist.htm","Statistics - To gain a broad view &#62; What are the available statistical functions?","What are the available statistical functions?",""],
["what_are_the_special_features_.htm","Forms &#38; Actions &#62; Maintain recipient&#39;s profile with actions &#62; What are the special features of the OpenEMM?","What are the special features of the OpenEMM?",""],
["what_are_users_.htm","Administration - Configuring the system &#62; Users &#62; What are users?","What are users?",""],
["what_is_a_form_.htm","Forms &#38; Actions &#62; Forms - Recipient management &#62; What is a form?","What is a form?",""],
["what_is_a_mailing_.htm","Mailings - Sending out newsletters &#62; What is a mailing?","What is a mailing?",""],
["what_is_a_mailing_list_.htm","Mailing lists - Managing list subscription &#62; What is a mailing list?","What is a mailing list?",""],
["what_is_a_traget_group_.htm","Target groups - Dynamic filters &#62; What is a traget group?","What is a traget group?",""],
["what_is_content_manager_.htm","Content Manager &#62; What is Content Manager?","What is Content Manager?",""]];
