pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["action_changing_recipient_prof.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Aktionen definieren &#62; Aktion: Empfängerprofil verändern","Aktion: Empfängerprofil verändern",""],
["action_including_a_script_in_a.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Aktionen definieren &#62; Aktion: Eigene Skripts integrieren","Aktion: Eigene Skripts integrieren",""],
["action_triggering_an_action-ba.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Aktionen definieren &#62; Aktion: Aktionsgesteuertes Mailing auslösen","Aktion: Aktionsgesteuertes Mailing auslösen",""],
["adding_contents_to_a_module_ty.htm","Content Manager &#62; Modultypen &#62; Modultyp um Inhalte ergänzen und als Content-Modul speichern","Modultyp um Inhalte ergänzen und als Content-Modul speichern",""],
["advanced_form_layout.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Erweiterte Formulargestaltung","Erweiterte Formulargestaltung",""],
["appendix_a_agnitas-tags.htm","Anhang A: AGNITAS-Tags","Anhang A: AGNITAS-Tags",""],
["archives_-_grouping_mailings.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen","Archiv - Mailings zusammenfassen",""],
["assigning_a_content_module_to_.htm","Content Manager &#62; Content-Module &#62; CM-Kategorien &#62; Content-Modul einer CM-Kategorie zuweisen","Content-Modul einer CM-Kategorie zuweisen",""],
["assigning_the_csv_columns_to_t.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Der Import-Assistent &#62; Zuweisung der CSV zu den Datenbank-Spalten","Zuweisung der CSV zu den Datenbank-Spalten",""],
["assigning_user_rights2.htm","Verwaltung - Das System konfigurieren &#62; Benutzer &#62; Benutzerrechte einstellen","Benutzerrechte einstellen",""],
["assign_existing_mailing.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Mailings einem Archiv zuweisen &#62; Bestehende Mailings zuordnen","Bestehende Mailings zuordnen",""],
["assign_mailing_to_a_archive.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Mailings einem Archiv zuweisen","Mailings einem Archiv zuweisen",""],
["assign_new_mailing.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Mailings einem Archiv zuweisen &#62; Neue Mailings zuordnen","Neue Mailings zuordnen",""],
["auto-export.htm","Empfänger - Kundendaten pflegen &#62; Exportfunktion für Empfängerdaten &#62; Auto-Export","Auto-Export",""],
["auto-import.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Auto-Import","Auto-Import",""],
["automatic_date-based_mailing_-.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Datumsgesteuerte Mailings","Datumsgesteuerte Mailings",""],
["automatic_mailing_-_an_example.htm","Sites &#38; Actions &#62; Automatischer Mailing-Versand - ein Beispiel","Automatischer Mailing-Versand",""],
["automatic_update_of_openemm.htm","Automatisches Update","Automatisches Update",""],
["blacklist_-_do_not_mail.htm","Empfänger - Kundendaten pflegen &#62; Blacklist - Zustellung verboten","Blacklist - Zustellung verboten",""],
["bounce-filter.htm","Verwaltung - Das System konfigurieren &#62; Bounce-Filter","Bounce-Filter",""],
["calling_up_a_form.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Ändern eines Profils &#62; Formular aufrufen","Formular aufrufen",""],
["calling_up_the_registration_f2.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung mit Double-Opt-In &#62; Anmeldeformular aufrufen","Anmeldeformular aufrufen",""],
["calling_up_the_registration_fo.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung &#62; Anmeldeformular aufrufen","Anmeldeformular aufrufen",""],
["calling_up_the_unsubscribe_for.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Abmeldung &#62; Abmeldeformular aufrufen","Abmeldeformular aufrufen",""],
["click_summation_for_trackable_.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden &#62; Summenfunktion für messbare Links","Summenfunktion für messbare Links",""],
["closed-loop_marketing_-_an_exa.htm","Sites &#38; Actions &#62; Closed-Loop-Marketing","Closed-Loop-Marketing",""],
["cm_categories.htm","Content Manager &#62; Content-Module &#62; CM-Kategorien","CM-Kategorien",""],
["cm_templates.htm","Content Manager &#62; CM-Schablonen","CM-Schablonen",""],
["combined_search_rules_with_bra.htm","Zielgruppen - dynamische Filter &#62; Kombinierte Suchregeln mit Klammern","Kombinierte Suchregeln mit Klammern",""],
["combining_search_rules.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Feldern &#62; Kombinierte Suchregeln","Kombinierte Suchregeln",""],
["comparing_mailings_openemm.htm","Statistik - Überblick gewinnen &#62; Vergleich","Vergleich",""],
["comparing_target_groups_openemm.htm","Statistik - Überblick gewinnen &#62; Mailing-Statistik &#62; Mehrere Zielgruppen vergleichen","Mehrere Zielgruppen vergleichen",""],
["connecting_links_to_actions.htm","Sites &#38; Actions &#62; Closed-Loop-Marketing &#62; Links mit Aktionen verbinden","Links mit Aktionen verbinden",""],
["content_manager.htm","Content Manager","Content Manager",""],
["content_modules.htm","Content Manager &#62; Content-Module","Content-Module",""],
["copying_a_mailing.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Kopie eines Mailings anlegen","Kopie eines Mailings anlegen",""],
["copying_of_target_groups.htm","Zielgruppen - dynamische Filter &#62; Kopieren von Zielgruppen","Kopieren von Zielgruppen",""],
["create_an_action-based_mailing.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung mit Double-Opt-In &#62; Aktionsgesteuertes Mailing anlegen","Aktionsgesteuertes Mailing anlegen",""],
["create_a_link_in_the_html_vers.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden &#62; Einen Link in der HTML-Version erstellen","Einen Link in der HTML-Version erstellen",""],
["create_a_link_in_the_text_vers.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden &#62; Einen Link in der Text-Version erstellen","Einen Link in der Text-Version erstellen",""],
["create_a_mailing_list_from_a_t.htm","Zielgruppen - dynamische Filter &#62; Mailing-Liste erzeugen oder Empfänger löschen","Mailing-Liste erzeugen oder Empfänger löschen",""],
["create_a_new_archive.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Archive verwalten &#62; Neues Archiv anlegen","Neues Archiv anlegen",""],
["create_a_new_cm_category.htm","Content Manager &#62; Content-Module &#62; CM-Kategorien &#62; Neue CM-Kategorie anlegen","Neue CM-Kategorie anlegen",""],
["create_a_new_module_type.htm","Content Manager &#62; Modultypen &#62; Einen neuen Modultyp erstellen","Einen neuen Modultyp erstellen",""],
["create_new_mailing_using_the_w.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Neues Mailing anlegen mit Assistent","Neues Mailing anlegen mit Assistent",""],
["create_new_recipients.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Neue Empfänger anlegen","Neue Empfänger anlegen",""],
["create_trackable_and_non-track.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden &#62; Messbare und nicht messbare Links","Messbare und nicht messbare Links",""],
["create__edit_and_send_mailings.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden","Mailings anlegen, bearbeiten und versenden",""],
["creating_administrators_and_te.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Administratoren und Testverteiler anlegen","Administratoren und Testverteiler anlegen",""],
["creating_and_managing_target_g.htm","Zielgruppen - dynamische Filter &#62; Zielgruppen anlegen und verwalten","Zielgruppen anlegen und verwalten",""],
["creating_a_basic_mailing.htm","Sites &#38; Actions &#62; Automatischer Mailing-Versand - ein Beispiel &#62; Basis-Mailing anlegen","Basis-Mailing anlegen",""],
["creating_a_csv-file.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Erzeugen einer CSV-Datei","Erzeugen einer CSV-Datei",""],
["creating_a_follow-up_mailing.htm","Sites &#38; Actions &#62; Automatischer Mailing-Versand - ein Beispiel &#62; Followup-Mailing anlegen","Followup-Mailing anlegen",""],
["creating_a_form_to_display_dat.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Ändern eines Profils &#62; Formular zum Anzeigen anlegen","Formular zum Anzeigen anlegen",""],
["creating_a_form_to_enter_data.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung &#62; Formular zur Dateneingabe anlegen","Formular zur Dateneingabe anlegen",""],
["creating_a_form_to_save_data.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Ändern eines Profils &#62; Formular zum Speichern anlegen","Formular zum Speichern anlegen",""],
["creating_a_form_to_save_data2.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung &#62; Formular zum Speichern anlegen","Formular zum Speichern anlegen",""],
["creating_a_html_form_dynamical.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Erweiterte Formulargestaltung &#62; HTML-Formular dynamisch erzeugen","HTML-Formular dynamisch erzeugen",""],
["creating_a_mailing_list.htm","Mailing-Listen - Abonnements verwalten &#62; Neue Mailing-Liste anlegen","Neue Mailing-Liste anlegen",""],
["creating_a_new_action.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Ändern eines Profils &#62; Neue Aktionen anlegen","Neue Aktionen anlegen",""],
["creating_a_new_action2.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung &#62; Neue Aktion anlegen","Neue Aktion anlegen",""],
["creating_a_new_action3.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Abmeldung &#62; Neue Aktion anlegen","Neue Aktion anlegen",""],
["creating_a_new_content_module.htm","Content Manager &#62; Content-Module &#62; Neues Content-Module anlegen","Neues Content-Module anlegen",""],
["creating_a_new_import_profile.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen","Neues Importprofil erstellen",""],
["creating_a_new_mailing.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen","Neues Mailing anlegen",""],
["creating_a_new_template.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen","Neue Schablone anlegen",""],
["creating_a_new_user_and_changi.htm","Verwaltung - Das System konfigurieren &#62; Benutzer &#62; Benutzer anlegen und Passwort ändern","Benutzer anlegen und Passwort ändern",""],
["creating_new_actions.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung mit Double-Opt-In &#62; Neue Aktionen anlegen","Neue Aktionen anlegen",""],
["creating_new_fields.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Empfängerprofil erweitern &#62; Neue Felder erzeugen","Neue Felder erzeugen",""],
["creating_new_forms.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung mit Double-Opt-In &#62; Neue Formulare anlegen","Neue Formulare anlegen",""],
["creating_new_forms2.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Abmeldung &#62; Neue Formulare anlegen","Neue Formulare anlegen",""],
["creating_text_and_html_modules.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Inhalte einfügen &#62; Textbausteine anlegen","Textbausteine anlegen",""],
["date_functions.htm","Zielgruppen - dynamische Filter &#62; Aufbau der Suchregeln &#62; Datumsfunktionen","Datumsfunktionen",""],
["deactivating_and_uninstalling_.htm","Verwaltung - Das System konfigurieren &#62; Plugin Manager &#62; Plugin deaktivieren und deinstallieren","Plugin deaktivieren und deinstallieren",""],
["defining_actions.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Aktionen definieren","Aktionen definieren",""],
["defining_actions2.htm","Sites &#38; Actions &#62; Closed-Loop-Marketing &#62; Aktionen definieren","Aktionen definieren",""],
["defining_actions3.htm","Sites &#38; Actions &#62; Automatischer Mailing-Versand - ein Beispiel &#62; Aktion definieren","Aktion definieren",""],
["deleting_an_archive.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Archive verwalten &#62; Archiv löschen","Archiv löschen",""],
["deleting_a_cm_category.htm","Content Manager &#62; Content-Module &#62; CM-Kategorien &#62; CM-Kategorie löschen","CM-Kategorie löschen",""],
["deleting_a_content_module.htm","Content Manager &#62; Content-Module &#62; Content-Modul löschen","Content-Modul löschen",""],
["deleting_a_mailing_list.htm","Mailing-Listen - Abonnements verwalten &#62; Mailing-Liste löschen","Mailing-Liste löschen",""],
["deleting_a_module_type.htm","Content Manager &#62; Modultypen &#62; Modultyp löschen","Modultyp löschen",""],
["deleting_a_recipient.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfänger entfernen","Empfänger entfernen",""],
["deleting_a_template.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen &#62; Schablone löschen","Schablone löschen",""],
["deleting_existing_fields.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Empfängerprofil erweitern &#62; Bestehende Felder löschen","Bestehende Felder löschen",""],
["detailed_recipient_statistics_openemm.htm","Statistik - Überblick gewinnen &#62; Empfänger-Statistik &#62; Detailgenaue Empfänger-Statistik","Detailgenaue Empfänger-Statistik",""],
["determining_the_csv-file_setti.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen &#62; Festlegen der CSV-Datei-Einstellungen","Festlegen der CSV-Datei-Einstellungen",""],
["determining_the_process_settin.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen &#62; Festlegen der Prozess-Einstellungen","Festlegen der Prozess-Einstellungen",""],
["de_openemm2015v1_headerframe.htm","Handbuch AGNITAS OpenEMM 2015","OpenEMM Online-Hilfe Suche ",""],
["display_and_amend_details.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Archive verwalten &#62; Details anzeigen und ändern","Details anzeigen und ändern",""],
["domain_statistics.htm","Statistik - Überblick gewinnen &#62; Domain-Statistik","Domain-Statistik",""],
["drop-down_list_for_relational_.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Feldern &#62; Auswahlliste für Vergleichsoperatoren","Auswahlliste für Vergleichsoperatoren",""],
["drop-down_list_instead_of_entr.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Erweiterte Formulargestaltung &#62; Auswahlliste statt Eingabefeld","Auswahlliste statt Eingabefeld",""],
["dynamic_content_generation.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Dynamische Content-Generierung","Dynamische Content-Generierung",""],
["dynamic_text_module.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Textbausteine verwenden &#62; Dynamische Textbausteine","Dynamische Textbausteine",""],
["editing_cm_templates.htm","Content Manager &#62; CM-Schablonen &#62; CM-Schablonen bearbeiten","CM-Schablonen bearbeiten",""],
["editing_recipient_profile.htm","Sites &#38; Actions &#62; Closed-Loop-Marketing &#62; Empfängerprofil erweitern","Empfängerprofil erweitern",""],
["edit_recipient_profile.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfängerprofil bearbeiten","Empfängerprofil bearbeiten",""],
["entering_basic_data.htm","Content Manager &#62; Modultypen &#62; Basisdaten eingeben","Basisdaten eingeben",""],
["entering_basic_data2.htm","Content Manager &#62; Content-Module &#62; Basisdaten eingeben","Basisdaten eingeben",""],
["entering_basic_mailing_data.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Basisdaten zum Mailing eingeben","Basisdaten zum Mailing eingeben",""],
["entering_basic_template_data.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen &#62; Basisdaten zur Schablone eingeben","Basisdaten zur Schablone eingeben",""],
["entering_further_mailing_data.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Eingabe von weiteren Mailingdaten","Eingabe von weiteren Mailingdaten",""],
["entering_further_template_data.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen &#62; Eingabe von weiteren Schablonendaten","Eingabe von weiteren Schablonendaten",""],
["errorhandling.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Der Import-Assistent &#62; Fehlerbehandlung","Fehlerbehandlung",""],
["example_form_for_a_user_profil.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Ändern eines Profils","Beispiel Formular: Ändern eines Profils",""],
["example_form_for_unsubscribing.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Abmeldung","Beispiel Formular: Abmeldung",""],
["example_opt-in_form.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung","Beispiel Formular: Anmeldung",""],
["example_subscribing_with_doubl.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Beispiel Formular: Anmeldung mit Double-Opt-In","Beispiel Formular: Anmeldung mit Double-Opt-In",""],
["exporting_statistical_data.htm","Statistik - Überblick gewinnen &#62; Statistische Daten exportieren","Statistische Daten exportieren",""],
["export_function_for_recipient_.htm","Empfänger - Kundendaten pflegen &#62; Exportfunktion für Empfängerdaten","Exportfunktion für Empfängerdaten",""],
["extending_recipients_profiles.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Empfängerprofil erweitern","Empfängerprofil erweitern",""],
["feedback_analysis_openemm.htm","Statistik - Überblick gewinnen &#62; Mailing-Statistik &#62; Feedback-Analyse","Feedback-Analyse",""],
["field_drop-down_list.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Feldern &#62; Auswahlliste für Felder","Auswahlliste für Felder",""],
["forms.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare","Formulare",""],
["forms_-_recipient_management.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger","Formular - Selbstverwaltung für Empfänger",""],
["form_of_address_-_individual_g.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Personalisierte Mailings gestalten &#62; Anredearten - individuelle Ansprache","Anredearten - individuelle Ansprache",""],
["fullview_always_display_html_m.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Fullview: HTML-Mails immer korrekt angezeigt","Fullview: HTML-Mails immer korrekt angezeigt",""],
["functions_of_the_produktname.htm","OpenEMM - Die Grundlagen &#62; Arbeitsweise des OpenEMM","Arbeitsweise des OpenEMM",""],
["further_details_for_creating_t.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen &#62; Weitere Details für Schablonen anlegen","Weitere Details für Schablonen anlegen",""],
["general_information.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfängerprofil anzeigen &#62; Allgemeine Angaben","Allgemeine Angaben",""],
["handling_with_duplicates.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen &#62; Behandlung von Dubletten","Behandlung von Dubletten",""],
["heatmap_openemm.htm","Statistik - Überblick gewinnen &#62; Mailing-Statistik &#62; Heatmap","Heatmap",""],
["how_do_recipients_get_into_you.htm","Empfänger - Kundendaten pflegen &#62; Mehr als nur E-Mail-Adressen &#62; Wie kommen Empfänger in die Datenbank?","Wie kommen Empfänger in die Datenbank?",""],
["importing_the_csv-file.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Der Import-Assistent &#62; Import der CSV-Datei","Import der CSV-Datei",""],
["import_dialog_structure.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Aufbau des Importdialogs","Aufbau des Importdialogs",""],
["import_function_for_recipient_.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten","Importfunktion für Empfängerdaten",""],
["inserting_agnitas-tags.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Personalisierte Mailings gestalten &#62; AGNITAS-Tag einfügen","AGNITAS-Tag einfügen",""],
["inserting_a_text_module_using_.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Textbausteine verwenden &#62; Textbausteine mit AGNITAS-Tags einfügen","Textbausteine mit AGNITAS-Tags einfügen",""],
["inserting_content.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Inhalte einfügen","Inhalte einfügen",""],
["insert_agnitas-tags_into_track.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden &#62; AGNITAS-Tags in messbare Links einbauen","AGNITAS-Tags in messbare Links einbauen",""],
["installing_and_activating_a_pl.htm","Verwaltung - Das System konfigurieren &#62; Plugin Manager &#62; Plugin installieren und aktivieren","Plugin installieren und aktivieren",""],
["ip_statistics.htm","Statistik - Überblick gewinnen &#62; IP-Übersicht","IP-Übersicht",""],
["is_and_null_or_not_null.htm","Zielgruppen - dynamische Filter &#62; Aufbau der Suchregeln &#62; IS und NULL oder NOT NULL","IS und NULL oder NOT NULL",""],
["linking_actions_and_trackable_.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Messbare Links mit Aktionen verknüpfen","Messbare Links mit Aktionen verknüpfen",""],
["linking_target_groups.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Zielgruppen miteinander verknüpfen","Zielgruppen miteinander verknüpfen",""],
["list_existing_mailings.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Übersicht bestehender Mailings","Übersicht bestehender Mailings",""],
["list_split_using_mod.htm","Zielgruppen - dynamische Filter &#62; Aufbau der Suchregeln &#62; List-Splits mit MOD","List-Splits mit MOD",""],
["mailings_-_sending_out_newslet.htm","Mailings - Newsletter versenden","Mailings - Newsletter versenden",""],
["mailings_under_control.htm","OpenEMM - Die Grundlagen &#62; Einführung in den OpenEMM","Einführung in den OpenEMM",""],
["mailing_lists_-_managing_list_.htm","Mailing-Listen - Abonnements verwalten","Mailing-Listen - Abonnements verwalten",""],
["mailing_lists_and_recipient_ty.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfängerprofil anzeigen &#62; Mailing-Listen und Empfängertypen","Mailing-Listen und Empfängertypen",""],
["mailing_statistics_openemm.htm","Statistik - Überblick gewinnen &#62; Mailing-Statistik","Mailing-Statistik",""],
["maintain_recipients_profile_wi.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen","Aktionen - Kundenprofile pflegen",""],
["managing_actions.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Aktionen definieren &#62; Aktionen verwalten","Aktionen verwalten",""],
["managing_archives.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Archive verwalten","Archive verwalten",""],
["managing_a_profile__deleting_a.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Profile verwalten, Profile löschen","Profile verwalten, Profile löschen",""],
["managing_fields.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen &#62; Felder verwalten","Felder verwalten",""],
["managing_forms.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Formulare verwalten","Formulare verwalten",""],
["managing_profile_fields.htm","Verwaltung - Das System konfigurieren &#62; Felder verwalten","Felder verwalten",""],
["managing_recipients.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten","Empfänger verwalten",""],
["managing_user.htm","Verwaltung - Das System konfigurieren &#62; Benutzer &#62; Benutzer verwalten","Benutzer verwalten",""],
["modifying_a_mailing_list.htm","Mailing-Listen - Abonnements verwalten &#62; Mailing-Liste modifizieren","Mailing-Liste modifizieren",""],
["module_types.htm","Content Manager &#62; Modultypen","Modultypen",""],
["more_than_just_e-mail_addresse.htm","Empfänger - Kundendaten pflegen &#62; Mehr als nur E-Mail-Adressen","Mehr als nur E-Mail-Adressen",""],
["navigation_bar_and_mailing_elements.htm","Bedienung - Navigieren im OpenEMM &#62; Navigationsleiste und Bedienelemente","Navigationsleiste und Bedienelemente",""],
["online_help.htm","Bedienung - Navigieren im OpenEMM &#62; Die Online-Hilfe","Die Online-Hilfe",""],
["other_profile_data.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfängerprofil anzeigen &#62; Weitere Profil-Daten","Weitere Profil-Daten",""],
["overview_of_agnitas-tags.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Personalisierte Mailings gestalten &#62; Überblick über die AGNITAS-Tags","Überblick über die AGNITAS-Tags",""],
["overview_this_is_how_the_modul.htm","OpenEMM - Die Grundlagen &#62; Überblick: So arbeiten die Module zusammen","Überblick: Beschreibung der verschiedenen Funktionsbereiche",""],
["personalisierte_mailings_gesta.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Personalisierte Mailings gestalten","Personalisierte Mailings gestalten",""],
["planning_fields_properly.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Empfängerprofil erweitern &#62; Felder richtig planen","Felder richtig planen",""],
["plugin_manager.htm","Verwaltung - Das System konfigurieren &#62; Plugin Manager","Plugin Manager (nur für Lizenz-Nutzer)",""],
["preview_-_for_in-depth_checkin.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Mailing testen und versenden &#62; Vorschaufunktion - genau prüfen","Vorschaufunktion - genau prüfen",""],
["produktname_-_the_basics.htm","OpenEMM - Die Grundlagen","OpenEMM - Die Grundlagen",""],
["recipients_-_managing_customer.htm","Empfänger - Kundendaten pflegen","Empfänger - Kundendaten pflegen",""],
["recipient_statistics_openemm.htm","Statistik - Überblick gewinnen &#62; Empfänger-Statistik","Empfänger-Statistik",""],
["saving_and_copying_module_type.htm","Content Manager &#62; Modultypen &#62; Modultyp speichern, Modultyp kopieren","Modultyp speichern, Modultyp kopieren",""],
["saving_and_copying_templates.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Neue Schablone anlegen &#62; Schablone speichern - Schablone kopieren","Schablone speichern - Schablone kopieren",""],
["saving_a_content_moduke_and_as.htm","Content Manager &#62; Content-Module &#62; Content-Modul speichern und einem Mailing zuweisen, Content-Modul kopieren","Content-Modul speichern und einem Mailing zuweisen, Content-Modul kopieren",""],
["saving_a_new_mailing.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Neues Mailing speichern","Neues Mailing speichern",""],
["searching_for_fields.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Feldern","Suchen nach Feldern",""],
["searching_for_mailing_lists.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Mailing-Listen","Suchen nach Mailing-Listen",""],
["searching_for_recipients.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen","Empfänger suchen",""],
["search_by_recipient_status.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Empfänger-Status","Suchen nach Empfänger-Status",""],
["search_by_recipient_type.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Empfänger-Typ","Suchen nach Empfänger-Typ",""],
["search_by_target-group.htm","Empfänger - Kundendaten pflegen &#62; Empfänger suchen &#62; Suchen nach Zielgruppe","Suchen nach Zielgruppe",""],
["search_rule_setup.htm","Zielgruppen - dynamische Filter &#62; Aufbau der Suchregeln","Aufbau der Suchregeln",""],
["selecting_target_groups.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Neues Mailing anlegen &#62; Zielgruppen einstellen","Zielgruppen einstellen",""],
["selection_of_mailing_lists.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Der Import-Assistent &#62; Auswahl der Mailing-Listen","Auswahl der Mailing-Listen",""],
["sending_file_attachments.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Datei-Anhänge versenden","Datei-Anhänge versenden",""],
["sending_normal_file_attachment.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Datei-Anhänge versenden &#62; Normalen Datei-Anhang versenden","Normalen Datei-Anhang versenden",""],
["sending_out_test_mails.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Mailing testen und versenden &#62; Probeversand von Test-Mails","Probeversand von Test-Mails",""],
["sending_the_last_newsletter_ju.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; Versand des letzten Newsletters nach der Anmeldung","Versand des letzten Newsletters nach der Anmeldung",""],
["send_mailing.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Mailing testen und versenden &#62; Mailing abschicken","Mailing abschicken",""],
["settings_-_configuring_the_sys.htm","Verwaltung - Das System konfigurieren","Verwaltung - Das System konfigurieren",""],
["settings_for_e-mail_and_gender.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Neues Importprofil erstellen &#62; Einstellungen für E-Mail und Geschlecht","Einstellungen für E-Mail und Geschlecht",""],
["show_available_cm_templates.htm","Content Manager &#62; CM-Schablonen &#62; Vorhandene CM-Schablonen anzeigen","Vorhandene CM-Schablonen anzeigen",""],
["show_available_content_modules.htm","Content Manager &#62; Content-Module &#62; Vorhandene Content-Module anzeigen","Vorhandene Content-Module anzeigen",""],
["show_available_module_types.htm","Content Manager &#62; Modultypen &#62; Vorhandene Modultypen anzeigen","Vorhandene Modultypen anzeigen",""],
["show_recipient_profile.htm","Empfänger - Kundendaten pflegen &#62; Empfänger verwalten &#62; Empfängerprofil anzeigen","Empfängerprofil anzeigen",""],
["show_template_data.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Schablonendaten einblenden","Schablonendaten einblenden",""],
["sites__actions.htm","Sites &#38; Actions","Sites &#38; Actions",""],
["starting_the_produktname.htm","Bedienung - Navigieren im OpenEMM &#62; Aufruf des OpenEMM","Aufruf des OpenEMM",""],
["statistical_evaluation.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Statistische Auswertung","Statistische Auswertung",""],
["statistics_-_to_gain_a_broad_v.htm","Statistik - Überblick gewinnen","Statistik - Überblick gewinnen",""],
["subscription_via_e-mail.htm","Verwaltung - Das System konfigurieren &#62; Bounce-Filter &#62; Anwendung: Anmeldung per E-Mail","Anwendung: Anmeldung per E-Mail",""],
["target_groups_-_dynamic_filter.htm","Zielgruppen - dynamische Filter","Zielgruppen - dynamische Filter",""],
["templates_-_re-usable_text_mod.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine","Schablonen - Wiederverwendbare Bausteine",""],
["testing_and_sending_a_mailing.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Mailing testen und versenden","Mailing testen und versenden",""],
["the_import_assistant.htm","Empfänger - Kundendaten pflegen &#62; Importfunktion für Empfängerdaten &#62; Der Import-Assistent","Der Import-Assistent",""],
["the_plugins_at_a_glance.htm","Verwaltung - Das System konfigurieren &#62; Plugin Manager &#62; Die Plugins im Überblick","Die Plugins im Überblick",""],
["this_is_how_forms_work.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Formulare &#62; So funktionieren Formulare","So funktionieren Formulare",""],
["types_of_address.htm","Empfänger - Kundendaten pflegen &#62; Anredearten","Anredearten",""],
["uploading_new_cm_templates.htm","Content Manager &#62; CM-Schablonen &#62; Neue CM-Schablonen hochladen","Neue CM-Schablonen hochladen",""],
["user-defined_fields.htm","Empfänger - Kundendaten pflegen &#62; Mehr als nur E-Mail-Adressen &#62; Selbst definierte Felder","Selbst definierte Felder",""],
["users.htm","Verwaltung - Das System konfigurieren &#62; Benutzer","Benutzer",""],
["user_log.htm","Verwaltung - Das System konfigurieren &#62; User Log","User Log",""],
["user_self-administration.htm","Bedienung - Navigieren im OpenEMM &#62; Benutzer-Selbstverwaltung","Benutzer-Selbstverwaltung",""],
["using_cm_templates_in_mailings.htm","Content Manager &#62; CM-Schablonen in Mailings einsetzen","CM-Schablonen in Mailings einsetzen",""],
["using_graphic_elements.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Grafiken verwenden","Grafiken verwenden",""],
["using_templates.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Schablone anwenden","Schablone anwenden",""],
["using_text_modules.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Textbausteine verwenden","Textbausteine verwenden",""],
["using_the_produktname_to_contr.htm","Bedienung - Navigieren im OpenEMM","Bedienung - Navigieren im OpenEMM",""],
["using_trackable_links.htm","Mailings - Newsletter versenden &#62; Mailings anlegen, bearbeiten und versenden &#62; Messbare Links verwenden","Messbare Links verwenden",""],
["what_are_archives_.htm","Mailings - Newsletter versenden &#62; Archiv - Mailings zusammenfassen &#62; Was sind Archive?","Was sind Archive?",""],
["what_are_templates_.htm","Mailings - Newsletter versenden &#62; Schablonen - Wiederverwendbare Bausteine &#62; Was sind Schablonen?","Was sind Schablonen?",""],
["what_are_the_available_statist.htm","Statistik - Überblick gewinnen &#62; Welche Statistikfunktionen gibt es?","Welche Statistikfunktionen gibt es?",""],
["what_are_the_special_features_.htm","Sites &#38; Actions &#62; Kundenprofile pflegen mit Aktionen &#62; Welche Funktionen bietet der OpenEMM?","Welche Funktionen bietet der OpenEMM?",""],
["what_are_users_.htm","Verwaltung - Das System konfigurieren &#62; Benutzer &#62; Was sind Benutzer","Was sind Benutzer",""],
["what_is_a_form_.htm","Sites &#38; Actions &#62; Formular - Selbstverwaltung für Empfänger &#62; Was ist das Formular?","Was ist das Formular?",""],
["what_is_a_mailing_.htm","Mailings - Newsletter versenden &#62; Was ist ein Mailing?","Was ist ein Mailing?",""],
["what_is_a_mailing_list_.htm","Mailing-Listen - Abonnements verwalten &#62; Was ist eine Mailing-Liste?","Was ist eine Mailing-Liste?",""],
["what_is_a_traget_group_.htm","Zielgruppen - dynamische Filter &#62; Was ist eine Zielgruppe?","Was ist eine Zielgruppe?",""],
["what_is_content_manager_.htm","Content Manager &#62; Was ist der Content Manager?","Was ist der Content Manager?",""]];
